LOCATION_MAPPING = {
	[1] = {"@Deliveries/Big Box"},
	[2] = {"@Deliveries/Big Box Stack"},
	[3] = {"@Deliveries/Box Bunch"},
	[4] = {"@Deliveries/Box Stack"},
	[5] = {"@Deliveries/Crate"},
	[6] = {"@Deliveries/Crate of Drinks"},
	[7] = {"@Deliveries/Crate Stack"},
	[8] = {"@Deliveries/Lots of Crates of Drinks"},
	[9] = {"@Deliveries/Pizza Stack"},
	[10] = {"@Deliveries/Pizza Stack Mega"},
	[11] = {"@Deliveries/Plant Pot"},
	[12] = {"@Deliveries/Plant Pot Bunch"},
	[13] = {"@Deliveries/Plant Pot Stack"},
	[14] = {"@Deliveries/Plant Pot Wide"},
	[15] = {"@Deliveries/Sack"},
	[16] = {"@Deliveries/Sack Stack"},
	[17] = {"@Deliveries/Drink"},

	[20] = {"@Blind Bags/Mountain Town/Bag 1/Bag 1"},
[21] = {"@Blind Bags/Mountain Town/Bag 2/Bag 2"},
[22] = {"@Blind Bags/Mountain Town/Bag 3/Bag 3"},
[23] = {"@Blind Bags/Mountain Town/Bag 4/Bag 4"},

[24] = {"@Blind Bags/Snowy Peaks/Bag 1/Bag 1"},
[25] = {"@Blind Bags/Snowy Peaks/Bag 2/Bag 2"},
[26] = {"@Blind Bags/Snowy Peaks/Bag 3/Bag 3"},
[27] = {"@Blind Bags/Snowy Peaks/Bag 4/Bag 4"},

[28] = {"@Blind Bags/Fishing Town/Bag 1/Bag 1"},
[29] = {"@Blind Bags/Fishing Town/Bag 2/Bag 2"},
[30] = {"@Blind Bags/Fishing Town/Bag 3/Bag 3"},
[31] = {"@Blind Bags/Fishing Town/Bag 4/Bag 4"},

	[40] = {"@Snowcats/Theo/Theo"},
[41] = {"@Snowcats/Cici/Cici"},
[42] = {"@Snowcats/Fortino/Fortino"},
[43] = {"@Snowcats/Ellie/Ellie"},
[44] = {"@Snowcats/Fit/Fit"},
[45] = {"@Snowcats/Tooey/Tooey"},
[46] = {"@Snowcats/Reed/Reed"},
[47] = {"@Snowcats/Fives/Fives"},
[48] = {"@Snowcats/Sixo/Sixo"},
[49] = {"@Snowcats/Ada/Ada"},
[50] = {"@Snowcats/Foreman/Foreman"},
[51] = {"@Snowcats/Gus/Gus"},
[52] = {"@Snowcats/Seb/Seb"},

[60] = {
    "@Radio Towers/Upton/Upton",
    {"radiotower_upton", "toggle"}
},

[61] = {
    "@Radio Towers/Easton/Easton",
    {"radiotower_easton", "toggle"}
},

[62] = {
    "@Radio Towers/Snowy Peaks/Snowy Peaks",
    {"radiotower_snowypeaks", "toggle"}
},

[63] = {
    "@Radio Towers/Fishing Town/Fishing Town",
    {"radiotower_fishingtown", "toggle"}
},

	[1111] = {"@Upton/To Upton/Delivery"},
	[11111] = {"@Upton/To Upton/Perfect Delivery"},
	[1112] = {"@Upton/To Weston/Delivery"},
	[11112] = {"@Upton/To Weston/Perfect Delivery"},
	[1113] = {"@Upton/To Easton/Delivery"},
	[11113] = {"@Upton/To Easton/Perfect Delivery"},
	[1121] = {"@Upton/To Winton/Delivery"},
	[11121] = {"@Upton/To Winton/Perfect Delivery"},
	[1122] = {"@Upton/To Munton/Delivery"},
	[11122] = {"@Upton/To Munton/Perfect Delivery"},
	[1123] = {"@Upton/To Lopton/Delivery"},
	[11123] = {"@Upton/To Lopton/Perfect Delivery"},
	[1131] = {"@Upton/To Clifton/Delivery"},
	[11131] = {"@Upton/To Clifton/Perfect Delivery"},
	[1132] = {"@Upton/To Damton/Delivery"},
	[11132] = {"@Upton/To Damton/Perfect Delivery"},
	[1133] = {"@Upton/To Smalton/Delivery"},
	[11133] = {"@Upton/To Smalton/Perfect Delivery"},

	[1211] = {"@Weston/To Upton/Delivery"},
	[11211] = {"@Weston/To Upton/Perfect Delivery"},
	[1212] = {"@Weston/To Weston/Delivery"},
	[11212] = {"@Weston/To Weston/Perfect Delivery"},
	[1213] = {"@Weston/To Easton/Delivery"},
	[11213] = {"@Weston/To Easton/Perfect Delivery"},
	[1221] = {"@Weston/To Winton/Delivery"},
	[11221] = {"@Weston/To Winton/Perfect Delivery"},
	[1222] = {"@Weston/To Munton/Delivery"},
	[11222] = {"@Weston/To Munton/Perfect Delivery"},
	[1223] = {"@Weston/To Lopton/Delivery"},
	[11223] = {"@Weston/To Lopton/Perfect Delivery"},
	[1231] = {"@Weston/To Clifton/Delivery"},
	[11231] = {"@Weston/To Clifton/Perfect Delivery"},
	[1232] = {"@Weston/To Damton/Delivery"},
	[11232] = {"@Weston/To Damton/Perfect Delivery"},
	[1233] = {"@Weston/To Smalton/Delivery"},
	[11233] = {"@Weston/To Smalton/Perfect Delivery"},

	[1311] = {"@Easton/To Upton/Delivery"},
	[11311] = {"@Easton/To Upton/Perfect Delivery"},
	[1312] = {"@Easton/To Weston/Delivery"},
	[11312] = {"@Easton/To Weston/Perfect Delivery"},
	[1313] = {"@Easton/To Easton/Delivery"},
	[11313] = {"@Easton/To Easton/Perfect Delivery"},
	[1321] = {"@Easton/To Winton/Delivery"},
	[11321] = {"@Easton/To Winton/Perfect Delivery"},
	[1322] = {"@Easton/To Munton/Delivery"},
	[11322] = {"@Easton/To Munton/Perfect Delivery"},
	[1323] = {"@Easton/To Lopton/Delivery"},
	[11323] = {"@Easton/To Lopton/Perfect Delivery"},
	[1331] = {"@Easton/To Clifton/Delivery"},
	[11331] = {"@Easton/To Clifton/Perfect Delivery"},
	[1332] = {"@Easton/To Damton/Delivery"},
	[11332] = {"@Easton/To Damton/Perfect Delivery"},
	[1333] = {"@Easton/To Smalton/Delivery"},
	[11333] = {"@Easton/To Smalton/Perfect Delivery"},

	[2111] = {"@Winton/To Upton/Delivery"},
	[12111] = {"@Winton/To Upton/Perfect Delivery"},
	[2112] = {"@Winton/To Weston/Delivery"},
	[12112] = {"@Winton/To Weston/Perfect Delivery"},
	[2113] = {"@Winton/To Easton/Delivery"},
	[12113] = {"@Winton/To Easton/Perfect Delivery"},
	[2121] = {"@Winton/To Winton/Delivery"},
	[12121] = {"@Winton/To Winton/Perfect Delivery"},
	[2122] = {"@Winton/To Munton/Delivery"},
	[12122] = {"@Winton/To Munton/Perfect Delivery"},
	[2123] = {"@Winton/To Lopton/Delivery"},
	[12123] = {"@Winton/To Lopton/Perfect Delivery"},
	[2131] = {"@Winton/To Clifton/Delivery"},
	[12131] = {"@Winton/To Clifton/Perfect Delivery"},
	[2132] = {"@Winton/To Damton/Delivery"},
	[12132] = {"@Winton/To Damton/Perfect Delivery"},
	[2133] = {"@Winton/To Smalton/Delivery"},
	[12133] = {"@Winton/To Smalton/Perfect Delivery"},

	[2211] = {"@Munton/To Upton/Delivery"},
	[12211] = {"@Munton/To Upton/Perfect Delivery"},
	[2212] = {"@Munton/To Weston/Delivery"},
	[12212] = {"@Munton/To Weston/Perfect Delivery"},
	[2213] = {"@Munton/To Easton/Delivery"},
	[12213] = {"@Munton/To Easton/Perfect Delivery"},
	[2221] = {"@Munton/To Winton/Delivery"},
	[12221] = {"@Munton/To Winton/Perfect Delivery"},
	[2222] = {"@Munton/To Munton/Delivery"},
	[12222] = {"@Munton/To Munton/Perfect Delivery"},
	[2223] = {"@Munton/To Lopton/Delivery"},
	[12223] = {"@Munton/To Lopton/Perfect Delivery"},
	[2231] = {"@Munton/To Clifton/Delivery"},
	[12231] = {"@Munton/To Clifton/Perfect Delivery"},
	[2232] = {"@Munton/To Damton/Delivery"},
	[12232] = {"@Munton/To Damton/Perfect Delivery"},
	[2233] = {"@Munton/To Smalton/Delivery"},
	[12233] = {"@Munton/To Smalton/Perfect Delivery"},

	[2311] = {"@Lopton/To Upton/Delivery"},
	[12311] = {"@Lopton/To Upton/Perfect Delivery"},
	[2312] = {"@Lopton/To Weston/Delivery"},
	[12312] = {"@Lopton/To Weston/Perfect Delivery"},
	[2313] = {"@Lopton/To Easton/Delivery"},
	[12313] = {"@Lopton/To Easton/Perfect Delivery"},
	[2321] = {"@Lopton/To Winton/Delivery"},
	[12321] = {"@Lopton/To Winton/Perfect Delivery"},
	[2322] = {"@Lopton/To Munton/Delivery"},
	[12322] = {"@Lopton/To Munton/Perfect Delivery"},
	[2323] = {"@Lopton/To Lopton/Delivery"},
	[12323] = {"@Lopton/To Lopton/Perfect Delivery"},
	[2331] = {"@Lopton/To Clifton/Delivery"},
	[12331] = {"@Lopton/To Clifton/Perfect Delivery"},
	[2332] = {"@Lopton/To Damton/Delivery"},
	[12332] = {"@Lopton/To Damton/Perfect Delivery"},
	[2333] = {"@Lopton/To Smalton/Delivery"},
	[12333] = {"@Lopton/To Smalton/Perfect Delivery"},

	[3111] = {"@Clifton/To Upton/Delivery"},
	[13111] = {"@Clifton/To Upton/Perfect Delivery"},
	[3112] = {"@Clifton/To Weston/Delivery"},
	[13112] = {"@Clifton/To Weston/Perfect Delivery"},
	[3113] = {"@Clifton/To Easton/Delivery"},
	[13113] = {"@Clifton/To Easton/Perfect Delivery"},
	[3121] = {"@Clifton/To Winton/Delivery"},
	[13121] = {"@Clifton/To Winton/Perfect Delivery"},
	[3122] = {"@Clifton/To Munton/Delivery"},
	[13122] = {"@Clifton/To Munton/Perfect Delivery"},
	[3123] = {"@Clifton/To Lopton/Delivery"},
	[13123] = {"@Clifton/To Lopton/Perfect Delivery"},
	[3131] = {"@Clifton/To Clifton/Delivery"},
	[13131] = {"@Clifton/To Clifton/Perfect Delivery"},
	[3132] = {"@Clifton/To Damton/Delivery"},
	[13132] = {"@Clifton/To Damton/Perfect Delivery"},
	[3133] = {"@Clifton/To Smalton/Delivery"},
	[13133] = {"@Clifton/To Smalton/Perfect Delivery"},

	[3211] = {"@Damton/To Upton/Delivery"},
	[13211] = {"@Damton/To Upton/Perfect Delivery"},
	[3212] = {"@Damton/To Weston/Delivery"},
	[13212] = {"@Damton/To Weston/Perfect Delivery"},
	[3213] = {"@Damton/To Easton/Delivery"},
	[13213] = {"@Damton/To Easton/Perfect Delivery"},
	[3221] = {"@Damton/To Winton/Delivery"},
	[13221] = {"@Damton/To Winton/Perfect Delivery"},
	[3222] = {"@Damton/To Munton/Delivery"},
	[13222] = {"@Damton/To Munton/Perfect Delivery"},
	[3223] = {"@Damton/To Lopton/Delivery"},
	[13223] = {"@Damton/To Lopton/Perfect Delivery"},
	[3231] = {"@Damton/To Clifton/Delivery"},
	[13231] = {"@Damton/To Clifton/Perfect Delivery"},
	[3232] = {"@Damton/To Damton/Delivery"},
	[13232] = {"@Damton/To Damton/Perfect Delivery"},
	[3233] = {"@Damton/To Smalton/Delivery"},
	[13233] = {"@Damton/To Smalton/Perfect Delivery"},

	[3311] = {"@Smalton/To Upton/Delivery"},
	[13311] = {"@Smalton/To Upton/Perfect Delivery"},
	[3312] = {"@Smalton/To Weston/Delivery"},
	[13312] = {"@Smalton/To Weston/Perfect Delivery"},
	[3313] = {"@Smalton/To Easton/Delivery"},
	[13313] = {"@Smalton/To Easton/Perfect Delivery"},
	[3321] = {"@Smalton/To Winton/Delivery"},
	[13321] = {"@Smalton/To Winton/Perfect Delivery"},
	[3322] = {"@Smalton/To Munton/Delivery"},
	[13322] = {"@Smalton/To Munton/Perfect Delivery"},
	[3323] = {"@Smalton/To Lopton/Delivery"},
	[13323] = {"@Smalton/To Lopton/Perfect Delivery"},
	[3331] = {"@Smalton/To Clifton/Delivery"},
	[13331] = {"@Smalton/To Clifton/Perfect Delivery"},
	[3332] = {"@Smalton/To Damton/Delivery"},
	[13332] = {"@Smalton/To Damton/Perfect Delivery"},
	[3333] = {"@Smalton/To Smalton/Delivery"},
	[13333] = {"@Smalton/To Smalton/Perfect Delivery"},
}