ITEM_MAPPING = {
	[100] = {{"energydrink", "toggle"}},
	[101] = {{"emptycan", "toggle"}},
	[102] = {{"lantern", "toggle"}},
	[103] = {{"lighter", "toggle"}},
	[104] = {{"firewood", "toggle"}},
	[105] = {{"shovel", "toggle"}},
	[106] = {{"birdseed", "toggle"}},
	[107] = {{"cookingpot", "toggle"}},
	[108] = {{"coffee", "toggle"}},
	[109] = {{"coffeepowder", "toggle"}},
	[110] = {{"tea", "toggle"}},
	[111] = {{"teabags", "toggle"}},
	[112] = {{"fish", "toggle"}},
	[113] = {{"fishingrod", "toggle"}},
	[114] = {{"fishsoup", "toggle"}},
	[115] = {{"ducttape", "toggle"}},
	[116] = {{"recoverydisc", "toggle"}},
	[117] = {{"handheldradio", "toggle"}},

	[1] = {{"map", "toggle"}},
	[2] = {{"snowtires", "toggle"}},
	[3] = {{"bumperbar", "toggle"}},
	[4] = {{"icechains", "toggle"}},

	[10] = {{"money", "toggle"}},
	[11] = {{"snowypeakstunnel", "toggle"}},
	[12] = {{"fishingtowntunnel", "toggle"}},
	[13] = {{"factorytunnel", "toggle"}},

	[20] = {{"radiotower", "consumable"}},
}