Tracker:AddLocations("locations/Blind Bags.json")
Tracker:AddLocations("locations/Clifton.json")
Tracker:AddLocations("locations/Damton.json")
Tracker:AddLocations("locations/Deliveries.json")
Tracker:AddLocations("locations/Easton.json")
Tracker:AddLocations("locations/Lopton.json")
Tracker:AddLocations("locations/Munton.json")
Tracker:AddLocations("locations/Radio Towers.json")
Tracker:AddLocations("locations/Smalton.json")
Tracker:AddLocations("locations/Snowcats.json")
Tracker:AddLocations("locations/Upton.json")
Tracker:AddLocations("locations/Weston.json")
Tracker:AddLocations("locations/Winton.json")
Tracker:AddLocations("locations/Overworld.json")
